//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Program_LargeMoney_DataView_G5310
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Label lblSrno;
    protected global::System.Web.UI.WebControls.Label lblStatus;
    protected global::System.Web.UI.WebControls.Label lblKind;
    protected global::System.Web.UI.WebControls.Label lblApType;
    protected global::System.Web.UI.WebControls.Label lblReportDate;
    protected global::System.Web.UI.WebControls.Label lblStday;
    protected global::System.Web.UI.WebControls.Label lblUnino;
    protected global::System.Web.UI.WebControls.Label lblCustomerName;
    protected global::System.Web.UI.WebControls.Label lblIbrno;
    protected global::System.Web.UI.WebControls.Label lblAcbrno;
    protected global::System.Web.UI.WebControls.Label lblCurcd;
    protected global::System.Web.UI.WebControls.Label lblBkcur;
    protected global::System.Web.UI.WebControls.Label lblBksrno;
    protected global::System.Web.UI.WebControls.Label lblIocd;
    protected global::System.Web.UI.WebControls.Label lblAmt;
    protected global::System.Web.UI.WebControls.Label lblAmtwhere;
    protected global::System.Web.UI.WebControls.Label lblReason;
    protected global::System.Web.UI.WebControls.Label lblEmpno;
    protected global::System.Web.UI.WebControls.Label lblEmpnm;
    protected global::System.Web.UI.WebControls.Label lblCreatedBy;
    protected global::System.Web.UI.WebControls.Label lblCreatedTime;
    protected global::System.Web.UI.WebControls.Label lblModifiedBy;
    protected global::System.Web.UI.WebControls.Label lblModifiedTime;
    protected global::System.Web.UI.WebControls.Label lblApprovedBy;
    protected global::System.Web.UI.WebControls.Label lblApprovedTime;
    protected global::System.Web.UI.WebControls.Button btnBack;
    protected global::System.Web.UI.WebControls.Button btnEdit;
    protected global::System.Web.UI.WebControls.Button btnRelease;
}