//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Program_LargeMoney_DataAdd_G5310
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Literal litTitle;
    protected global::System.Web.UI.WebControls.Literal litKind;
    protected global::System.Web.UI.WebControls.DropDownList ddlKind;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvKind;
    protected global::System.Web.UI.WebControls.Literal litApType;
    protected global::System.Web.UI.WebControls.TextBox txtApType;
    protected global::System.Web.UI.WebControls.Literal litReportDate;
    protected global::System.Web.UI.WebControls.TextBox txtReportDate;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReportDate;
    protected global::System.Web.UI.WebControls.Literal litSrno;
    protected global::System.Web.UI.WebControls.TextBox txtSrno;
    protected global::System.Web.UI.WebControls.Literal litUnino;
    protected global::System.Web.UI.WebControls.TextBox txtUnino;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvUnino;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revUnino;
    protected global::System.Web.UI.WebControls.Literal litCustomerName;
    protected global::System.Web.UI.WebControls.TextBox txtCustomerName;
    protected global::System.Web.UI.WebControls.Literal litStday;
    protected global::System.Web.UI.WebControls.TextBox txtStday;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvStday;
    protected global::System.Web.UI.WebControls.Literal litIocd;
    protected global::System.Web.UI.WebControls.DropDownList ddlIocd;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvIocd;
    protected global::System.Web.UI.WebControls.Literal litIbrno;
    protected global::System.Web.UI.WebControls.TextBox txtIbrno;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvIbrno;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revIbrno;
    protected global::System.Web.UI.WebControls.Literal litAcbrno;
    protected global::System.Web.UI.WebControls.TextBox txtAcbrno;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAcbrno;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revAcbrno;
    protected global::System.Web.UI.WebControls.Literal litCurcd;
    protected global::System.Web.UI.WebControls.DropDownList ddlCurcd;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCurcd;
    protected global::System.Web.UI.WebControls.Literal litBkcur;
    protected global::System.Web.UI.WebControls.DropDownList ddlBkcur;
    protected global::System.Web.UI.WebControls.Literal litBksrno;
    protected global::System.Web.UI.WebControls.TextBox txtBksrno;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revBksrno;
    protected global::System.Web.UI.WebControls.Literal litAmt;
    protected global::System.Web.UI.WebControls.TextBox txtAmt;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAmt;
    protected global::System.Web.UI.WebControls.RegularExpressionValidator revAmt;
    protected global::System.Web.UI.WebControls.Literal litAmtwhere;
    protected global::System.Web.UI.WebControls.TextBox txtAmtwhere;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAmtwhere;
    protected global::System.Web.UI.WebControls.Literal litReason;
    protected global::System.Web.UI.WebControls.TextBox txtReason;
    protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReason;
    protected global::System.Web.UI.WebControls.Literal litEmpno;
    protected global::System.Web.UI.WebControls.TextBox txtEmpno;
    protected global::System.Web.UI.WebControls.Literal litEmpnm;
    protected global::System.Web.UI.WebControls.TextBox txtEmpnm;
    protected global::System.Web.UI.WebControls.Button btnSubmit;
    protected global::System.Web.UI.WebControls.Button btnReset;
    protected global::System.Web.UI.WebControls.Button btnBack;
}