//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Program_LargeMoney_DataQuery_G5310
{
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    protected global::System.Web.UI.WebControls.Label lblEmpId;
    protected global::System.Web.UI.WebControls.Label lblEmpName;
    protected global::System.Web.UI.WebControls.Label lblBrno;
    protected global::System.Web.UI.WebControls.Label lblRole;
    protected global::System.Web.UI.WebControls.TextBox txtReportDateFrom;
    protected global::System.Web.UI.WebControls.TextBox txtReportDateTo;
    protected global::System.Web.UI.WebControls.TextBox txtStdayFrom;
    protected global::System.Web.UI.WebControls.TextBox txtStdayTo;
    protected global::System.Web.UI.WebControls.TextBox txtSearchUnino;
    protected global::System.Web.UI.WebControls.TextBox txtSearchCustomerName;
    protected global::System.Web.UI.WebControls.TextBox txtSearchSrno;
    protected global::System.Web.UI.WebControls.TextBox txtSearchIbrno;
    protected global::System.Web.UI.WebControls.TextBox txtSearchAcbrno;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearchCurcd;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearchIocd;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearchKind;
    protected global::System.Web.UI.WebControls.DropDownList ddlSearchStatus;
    protected global::System.Web.UI.WebControls.Button btnSearch;
    protected global::System.Web.UI.WebControls.Button btnClear;
    protected global::System.Web.UI.WebControls.Button btnAdd;
    protected global::System.Web.UI.WebControls.Button btnExport;
    protected global::System.Web.UI.WebControls.Label lblResultInfo;
    protected global::System.Web.UI.WebControls.GridView gvData;
}